# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.2
_src_path: gh:jupyterlab/extension-template
advanced: false
author_email: dev@example.com
author_name: ui-ml-platform
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab-missed-output-replay
project_short_description: A JupyterLab extension.
python_name: jupyterlab_missed_output_replay
repository: https://github.com/vitu-mafeni/ui-ml-platform
test: false

